[functions.create-checkout-session]
enabled = true
verify_jwt = true
import_map = "./functions/create-checkout-session/deno.json"
entrypoint = "./functions/create-checkout-session/index.ts"

[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.create-customer-portal]
enabled = true
verify_jwt = true
import_map = "./functions/create-customer-portal/deno.json"
entrypoint = "./functions/create-customer-portal/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete-account/index.ts"
